# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compost_sensor', '0003_auto_20161203_2217'),
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='name',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compost_sensor.CompostSensor', verbose_name='the compost sensor that generated this data'),
        ),
    ]
