# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compost_sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('sensors', models.ManyToManyField(to='compost_sensor.CompostSensor')),
            ],
        ),
    ]
