# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compost_user', '0002_compostuser_compost_bins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compostuser',
            name='compost_bins',
        ),
    ]
