# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compost_user', '0003_remove_compostuser_compost_bins'),
        ('compost_bin', '0002_auto_20161203_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compostbin',
            name='sensors',
        ),
        migrations.AddField(
            model_name='compostbin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compost_user.CompostUser', verbose_name='the compost bin owner'),
        ),
    ]
