# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compost_bin', '0003_auto_20161203_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compostbin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compost_user.CompostUser', verbose_name='the compost bin owner'),
        ),
    ]
