# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
        ('compost_sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compostsensor',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='compostsensor',
            name='value',
        ),
        migrations.AddField(
            model_name='compostsensor',
            name='sensor_values',
            field=models.ManyToManyField(to='sensor_data.SensorData'),
        ),
    ]
