# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compost_sensor', '0004_auto_20161203_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compostsensor',
            name='type',
            field=models.CharField(choices=[('temp', 'Temperature'), ('hum', 'Humidity'), ('vib', 'Vibration')], max_length=1),
        ),
    ]
