# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compost_sensor', '0005_auto_20161204_0120'),
        ('compost_sensor', '0005_auto_20161204_0119'),
    ]

    operations = [
    ]
